name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  bloc_oracle:
    path: ../
  flutter_bloc: ">=5.0.0 <7.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true