name: bloc_oracle
description: A widget that allows you to display the result of Bloc observer on the screen
version: 0.1.0
author: 4uzhoy
repository: https://github.com/4uzhoy/bloc_oracle
homepage: https://github.com/4uzhoy/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ">=5.0.0 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

